### ISSUE TITLE
An example is needed

### ISSUE THREAD

**Issue by swilson86** [i8beef/node-red-contrib-animate-gif#4]
There is not enough of an explanation to test this node. A simple example would be extremely useful. Thanks!

**Comment by i8beef** [comment]
There's not much documentation because there's really not much to it. You send in a message with a `msg.payload` that is an array of binary Buffers that you want combined, along with a few settings in the node to setup things like GIF looping, delays between images, etc., and it returns a message with a `msg.payload` set to the binary Buffer resulting image.

**Comment by swilson86** [comment]
Thanks... it is in this particular area that an explanation is needed. Let's say I have 4 gif images 1.gif through 4.gif which when combined make a single animated gif. This implies a file operation to get 1.gif through 4.gif in some kind of previous node, or maybe something like the node-red-contrib-buffer-parser etc. It's a huge rabbit hole to trying to decipher what you mean by "an array of binary Buffers".

May I suggest a simple example of a flow?

**Comment by i8beef** [comment]
Well personally I use a loop node that calls an HTTP endpoint on a timer (a camera snapshot URL) that outputs Buffers from the HTTP nodes and builds up an array of Buffers, and then on loop exit compiles those into a new message object to hand to this node. That example is going to use non-standard nodes you won't have. The JS Buffer object type is just an array of bytes, but you have to source those yourself in whatever way makes sense for your needs. You could just as easily read them from file system with file system nodes, using a function node to make fs calls to get Buffers, etc.

Perhaps it would be easier if you told me where you are trying to GET images from and I can make a suggestion on how to compile those together.

**Comment by swilson86** [comment]
I am trying to produce an animated gif of a plumbing system containing 2 water tanks, check valves, some pumps, connecting tubes, etc. It may be possible by building a single animated gif made up out of a larger collection of gifs stored on the file system. Node-red functions will determine which gifs to overlay to display the current situation of water movement and water tank levels. I don't know if it is possible but the idea of "smart animated gifs" is feasible.

**Comment by i8beef** [comment]
Well, the "file in" node in node-red will read a file from disk and return a binary Buffer. You just have to figure out how to execute multiple of those in a row to gather the individual frames of the GIF, and then pass them all as a single array in the `msg.payload`. I'm assuming in your example you have a series of single images pre-rendered that you want to pick and choose which to display in a certain order, and output a final GIF of these (At least that's what this node would help you do).

One way to do this, is like this:

1. Whatever trigger to start your flow
2. A function node that resets a flow variable, something like `flow.set("images", []); return msg;`
3. Your logic for choosing specific image files. Perhaps one function node that chooses a set of file locations based on other information.
4. A loop node (there are a couple dozen contrib nodes for this, or you could use a recursion based subflow to do it honestly) that will iterate to however many images you've chosen in step 3, where each loop uses a "file in" to read the contents as a binary Buffer and a "function" node that writes that gets the flow variable, "push" that Buffer to the array, and writes it back
5. An exit from that loop that consists of a "function" node that grabs that flow variable again sets it to the `msg.payload` like `let myBuffers = flow.get(images"); return { payload: myBuffers };`, then THIS node to combine all those frame by frame, and then you can do whatever you need to with the binary Buffer coming out of this.

I can think of a half dozen ways to do this, this is just one. Some changes would have to be made for things like "I want this to be an HTTP endpoint", etc. since in those cases you might have to carefully maintain the same initial message from HTTP IN to HTTP OUT to make it work right. It really depends on your setup here.

**Comment by swilson86** [comment]
Thanks. I am starting to see how things work. My approach may be wrong in trying to animate a plumbing system using gifs. That's a lot of "bit-banging" for a little Raspberry Pi running on a SD memory card with limited write times. Seems very much to be a brute force solution. Hmmmm... I will try to find a simpler solution. But in any case, you have now documented better how your node works and our conversations should be helpful for future readers.

**Comment by 111ar10** [comment]
Hey,

I was trying to set up array of 2 binary buffers, but getting an error:
Input buffer contains unsupported image format

![image](https://user-images.githubusercontent.com/51876074/105079593-ec869c00-5a8f-11eb-8d6c-7fa4251de9c9.png)

http node on output has - a binary buffer
![image](https://user-images.githubusercontent.com/51876074/105079787-33749180-5a90-11eb-83b4-3673287be18c.png)

and then I am combining those into an array
![image](https://user-images.githubusercontent.com/51876074/105079878-569f4100-5a90-11eb-926b-35c0038d9480.png)

Do you know what might be the issue?

**Comment by i8beef** [comment]
@111ar10 please open a new issue if you are having issues so we don't spam others with conversation.
